# Generated by Django 5.1.4 on 2025-01-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_icon', models.CharField(max_length=50)),
                ('home_title', models.CharField(max_length=50)),
            ],
        ),
    ]
