# Generated by Django 5.1.4 on 2025-01-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='home_icon',
            new_name='home_name',
        ),
        migrations.RemoveField(
            model_name='home',
            name='home_title',
        ),
        migrations.AddField(
            model_name='home',
            name='home_mail',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
