# Generated by Django 5.1.4 on 2025-01-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='home',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='name',
            new_name='user_name',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
