# Generated by Django 5.1.4 on 2025-01-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_name', models.CharField(max_length=50)),
                ('home_mail', models.EmailField(default='default@example.com', max_length=254)),
            ],
        ),
    ]
