# Generated by Django 5.1.4 on 2025-01-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_delete_home_delete_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
