# Generated by Django 5.1.4 on 2025-01-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_userdata_email_alter_userdata_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='image',
            field=models.ImageField(default='defalut.jpg', upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(default='abc@123', max_length=50),
        ),
    ]
