# Generated by Django 5.1.4 on 2025-01-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_userdata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(default='Anonymus', max_length=50, unique=True),
        ),
    ]
