# Generated by Django 5.1.4 on 2025-01-13 12:35

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_userdata_gender_alter_userdata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='country',
            field=django_countries.fields.CountryField(default='IN', max_length=2),
        ),
    ]
