# Generated by Django 5.1.4 on 2025-01-14 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_userdata_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='country',
        ),
    ]
