# Generated by Django 5.1.4 on 2025-01-14 07:14

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_remove_userdata_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='country',
            field=django_countries.fields.CountryField(default='IN', max_length=2),
        ),
    ]
