# Generated by Django 5.1.4 on 2025-01-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_alter_userdata_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(default='Anonymus', max_length=50),
        ),
    ]
