# Generated by Django 5.1.4 on 2025-01-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_alter_userdata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='password_strength',
            field=models.IntegerField(default=0),
        ),
    ]
